export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const UPDATE_NAVTAB_ID = 'UPDATE_NAVTAB_ID';
export type UPDATE_NAVTAB_ID = typeof UPDATE_NAVTAB_ID;

export const UPDATE_SIDETAB_ID = 'UPDATE_SIDETAB_ID';
export type UPDATE_SIDETAB_ID = typeof UPDATE_SIDETAB_ID;