export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const UPDATE_NAVTAB_ID = 'UPDATE_NAVTAB_ID';
export type UPDATE_NAVTAB_ID = typeof UPDATE_NAVTAB_ID;

export const UPDATE_ABOUTTAB_ID = 'UPDATE_ABOUTTAB_ID';
export type UPDATE_ABOUTTAB_ID = typeof UPDATE_ABOUTTAB_ID;

export const UPDATE_GETDATATAB_ID = 'UPDATE_GETDATATAB_ID';
export type UPDATE_GETDATATAB_ID = typeof UPDATE_GETDATATAB_ID;

export const UPDATE_UPLOADDATATAB_ID = 'UPDATE_UPLOADDATATAB_ID';
export type UPDATE_UPLOADDATATAB_ID = typeof UPDATE_UPLOADDATATAB_ID;

export const UPDATE_WIKITAB_ID = 'UPDATE_WIKITAB_ID';
export type UPDATE_WIKITAB_ID = typeof UPDATE_WIKITAB_ID;

export const TOGGLE_GENERAL_SEARCH_COLLAPSIBLE = 'TOGGLE_GENERAL_SEARCH_COLLAPSIBLE';
export type TOGGLE_GENERAL_SEARCH_COLLAPSIBLE = typeof TOGGLE_GENERAL_SEARCH_COLLAPSIBLE;

export const TOGGLE_FILE_SEARCH_COLLAPSIBLE = 'TOGGLE_FILE_SEARCH_COLLAPSIBLE';
export type TOGGLE_FILE_SEARCH_COLLAPSIBLE = typeof TOGGLE_FILE_SEARCH_COLLAPSIBLE;